// See dev/metadata_prefetch.md.
#pragma once

#include "damacy.h"
#include "prefetch/prefetch_handle.h"
#include "util/lru.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

  struct prefetch_cache;

  // Layout: [error:1 | pending:63] — one atomic, one load.
  struct prefetch_gate
  {
    _Atomic uint64_t state;
  };

  enum prefetch_state
  {
    PREFETCH_STATE_PENDING = 0,
    PREFETCH_STATE_READY = 1,
    PREFETCH_STATE_ERROR = 2,
  };

  struct prefetch_ops
  {
    int (*key_eq)(const struct prefetch_ops* self,
                  const void* stored_key,
                  const void* probe_key);
    void* (*key_clone)(const struct prefetch_ops* self, const void* probe_key);
    void (*key_destroy)(const struct prefetch_ops* self, void* stored_key);
    void (*value_destroy)(const struct prefetch_ops* self,
                          void* value); // NULL-safe
  };

  // Return 0 + value in *out_value, or non-zero + damacy_status in *out_err.
  struct prefetch_fetcher
  {
    int (*fetch)(struct prefetch_fetcher* self,
                 const void* key,
                 void** out_value,
                 int* out_err);
  };

  // Opaque completion token for asynchronous fetchers. Tokens are generated by
  // prefetch_cache_request_result and are valid until the async fetcher calls
  // prefetch_cache_complete, or until the caller has externally drained all
  // fetches before destroying the cache.
  struct prefetch_completion
  {
    struct prefetch_cache* cache;
    uint32_t slot;
    uint32_t generation;
  };

  // start() returns 0 once it owns the completion. It must eventually call
  // prefetch_cache_complete. Non-zero means the cache keeps ownership and marks
  // the slot ERROR.
  struct prefetch_async_fetcher
  {
    int (*start)(struct prefetch_async_fetcher* self,
                 const void* key,
                 struct prefetch_completion completion);
  };

  // err_code == 0 completes READY with value. Non-zero completes ERROR with
  // err_code and destroys value if non-NULL.
  void prefetch_cache_complete(struct prefetch_completion completion,
                               void* value,
                               int err_code);

  // post() returns 0: callee owns ctx (fn or ctx_free will free it).
  // post() returns non-zero: ownership stays with caller; the executor must
  // not have invoked ctx_free, or the caller's recovery path double-frees.
  // post() is called without the cache lock held. When invoked from the
  // prefetcher worker, the prefetcher's lock is held. post() must be
  // non-blocking and must not call back into the cache or prefetcher.
  struct prefetch_executor
  {
    int (*post)(struct prefetch_executor* self,
                void (*fn)(void*),
                void* ctx,
                void (*ctx_free)(void*));
  };

  struct prefetch_cache_config
  {
    uint32_t capacity;
    uint32_t max_probe;
    const struct prefetch_ops* ops;
    struct prefetch_fetcher* fetcher;
    struct prefetch_async_fetcher* async_fetcher;
    struct prefetch_executor* executor;
  };

  struct prefetch_cache* prefetch_cache_create(
    const struct prefetch_cache_config* cfg);

  void prefetch_cache_destroy(struct prefetch_cache* c);

  struct prefetch_request_result
  {
    struct prefetch_handle handle;
    enum damacy_status status;
  };

  // Returns DAMACY_OK + a valid handle on success. Saturation (every entry has
  // max_owner_id >= watermark) returns DAMACY_BUDGET; host allocation failures
  // return DAMACY_OOM. gate may be NULL.
  struct prefetch_request_result prefetch_cache_request_result(
    struct prefetch_cache* c,
    uint64_t key_hash,
    const void* key,
    uint64_t owner_id,
    struct prefetch_gate* gate);

  // Compatibility wrapper: returns PREFETCH_HANDLE_NONE on any non-OK status.
  struct prefetch_handle prefetch_cache_request(struct prefetch_cache* c,
                                                uint64_t key_hash,
                                                const void* key,
                                                uint64_t owner_id,
                                                struct prefetch_gate* gate);

  // NULL on pending, error, stale generation, OR when the ready value happens
  // to be NULL (callers using NULL as a 'no-value' sentinel). Use
  // prefetch_cache_query for the unambiguous state.
  const void* prefetch_cache_try_get(const struct prefetch_cache* c,
                                     struct prefetch_handle h);

  // NULL unless READY. Doesn't widen the ordinal range or bump LRU recency;
  // caller is responsible for pinning. In particular, a fetcher that peeks
  // into an upstream cache must run before the scheduler advances the
  // watermark past the owner ids that pinned the upstream entry.
  const void* prefetch_cache_peek(const struct prefetch_cache* c,
                                  uint64_t key_hash,
                                  const void* key);

  enum prefetch_state prefetch_cache_query(const struct prefetch_cache* c,
                                           struct prefetch_handle h,
                                           const void** out_value,
                                           int* out_err);

  // Monotonic; lower values ignored.
  void prefetch_cache_advance_watermark(struct prefetch_cache* c,
                                        uint64_t new_watermark);

  int prefetch_handle_valid(struct prefetch_handle h);

  void prefetch_gate_init(struct prefetch_gate* g);
  int prefetch_gate_is_ready(const struct prefetch_gate* g);
  int prefetch_gate_has_error(const struct prefetch_gate* g);
  uint64_t prefetch_gate_pending(const struct prefetch_gate* g);
  void prefetch_gate_set_error(struct prefetch_gate* g);

  struct prefetch_cache_stats
  {
    struct lru_counters counters;
    uint32_t size;
    uint32_t capacity;
    uint64_t watermark;
    uint64_t pending;
    uint64_t errored;
  };

  void prefetch_cache_stats_get(const struct prefetch_cache* c,
                                struct prefetch_cache_stats* out);

#ifdef __cplusplus
}
#endif
